name: PR Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  review_comment:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GitHub CLI
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create review comment
      run: |
        echo "Review comment content" > comment.txt
        gh pr review ${{ github.event.pull_request.number }} --body "$(cat comment.txt)"

    - name: run_py
      run: |
        python .github/workflows/send_mail.py
    
  email_notification:
    needs: review_comment
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Send email notification
      run: |
        echo "The conversation (ID: ${{ github.event.pull_request.id }}) has been resolved. Please check it out." > email.txt
        # Replace the following line with your own email sending logic using an SMTP library or email service provider API
        
        cat email.txt  # For demonstration purposes only
